# Generated by Django 5.0.6 on 2024-05-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('theory_shares_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chemical_B_NCO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chemical_B_functionality', models.IntegerField(default=2)),
                ('chemical_B_molecular_mass', models.IntegerField(max_length=6)),
                ('chemical_B_shares', models.IntegerField(max_length=6)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ptmg1000', 'PTMG1000'), ('ptmg2000', 'PTMG2000'), ('330N', '330N'), ('BDO', 'BDO'), ('water', '水'), ('silicone_oil', '硅油'), ('color_paster', '色膏'), ('catalyst_1', '催化剂1'), ('catalyst_2', '催化剂2')], max_length=50)),
                ('chemical_A_functionality', models.IntegerField(default=2)),
                ('chemical_A_hydroxyl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chemical_A_molecular_mass', models.IntegerField(max_length=6)),
                ('chemical_A_shares', models.IntegerField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_manager.job')),
            ],
        ),
    ]
