# Generated by Django 5.0.6 on 2024-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical_a',
            old_name='chemical_A_functionality',
            new_name='functionality',
        ),
        migrations.RenameField(
            model_name='chemical_a',
            old_name='chemical_A_hydroxyl',
            new_name='hydroxyl',
        ),
        migrations.RemoveField(
            model_name='chemical_a',
            name='chemical_A_molecular_mass',
        ),
        migrations.RemoveField(
            model_name='chemical_a',
            name='chemical_A_shares',
        ),
        migrations.AddField(
            model_name='chemical_a',
            name='molecular_mass',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemical_a',
            name='shares',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='chemical_B_molecular_mass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='chemical_B_shares',
            field=models.IntegerField(),
        ),
    ]
