# Generated by Django 5.0.6 on 2024-05-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0002_rename_chemical_a_functionality_chemical_a_functionality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='chemial_A_mass',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemical_a',
            name='name',
            field=models.CharField(blank=True, choices=[(None, '---------'), ('PTMG1000', 'PTMG1000'), ('PTMG2000', 'PTMG2000'), ('330N', '330N'), ('BDO', 'BDO'), ('water', '水'), ('silicone_oil', '硅油'), ('color_paster', '色膏'), ('catalyst_1', '催化剂1'), ('catalyst_2', '催化剂2')], max_length=50),
        ),
    ]
