# Generated by Django 5.0.6 on 2024-05-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0003_job_chemial_a_mass_alter_chemical_a_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='chemical_B_shares',
        ),
        migrations.AddField(
            model_name='job',
            name='chemical_B_mass',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='chemical_B_NCO',
            field=models.DecimalField(decimal_places=2, default=12.8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='chemical_B_molecular_mass',
            field=models.IntegerField(default=7000),
        ),
        migrations.AlterField(
            model_name='job',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
