# Generated by Django 5.0.6 on 2024-06-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0005_job_n0_job_n1_job_n2_job_n3_job_n4_job_n5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='created', max_length=40),
        ),
    ]
