# Generated by Django 5.0.6 on 2024-05-23 14:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoB', models.CharField(max_length=200)),
                ('Site', models.CharField(max_length=200)),
                ('DRI', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('Creator', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('Description', models.TextField()),
                ('Created_time', models.DateTimeField(auto_now_add=True)),
                ('Updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated_time', models.DateTimeField(auto_now=True)),
                ('State', models.CharField(choices=[('init', 'Init'), ('data_collection', 'Data Collection'), ('model_training', 'Model Training'), ('under_deployment', 'Under Deployment'), ('control_run_on_production', 'Control Run On Production'), ('OK2ML', 'OK2ML'), ('Pause', 'Pause'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='init', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
